services:

  mosquitto:
    image: eclipse-mosquitto:2.1.2-alpine
    container_name: smartpulse-mosquitto

    ports:
      - "1883:1883"

    volumes:
      - ./infrastructure/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data

    restart: unless-stopped


  rabbitmq:
    image: rabbitmq:4.3.5-management-alpine
    container_name: smartpulse-rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: smartpulse
      RABBITMQ_DEFAULT_PASS: smartpulse

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

    restart: unless-stopped


volumes:
  mosquitto-data:
  rabbitmq-data: