spring.application.name=SmartPulse Backend
spring.mongodb.database=smartpulse

smartpulse.mqtt.url=tcp://localhost:1883
smartpulse.mqtt.client-id=smartpulse-backend
smartpulse.mqtt.topic=smartpulse/devices/+/telemetry

spring.devtools.restart.enabled=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=smartpulse
spring.rabbitmq.password=smartpulse

smartpulse.rabbitmq.exchange=smartpulse.telemetry
smartpulse.rabbitmq.queue=smartpulse.telemetry.processing
smartpulse.rabbitmq.routing-key=telemetry.received