spring.application.name=SmartPulse Backend
spring.mongodb.database=smartpulse

smartpulse.mqtt.url=tcp://localhost:1883
smartpulse.mqtt.client-id=smartpulse-backend
smartpulse.mqtt.topic=smartpulse/devices/+/telemetry

spring.devtools.restart.enabled=false